% "	Was verhält sich zu CDU, wie Donald Trump zu den USA?
% "	Was verhält sich zu Deutschland, wie Silvio Berlusconi zu Italien?
% "	Was verhält sich zu Deutschland, wie Queen Elizabeth II zu Großbritannien?
% "	Was verhält sich zu AfD, wie Boris Johnson zu Brexit?
% "	Was verhält sich zu Deutschland wie Abrissbirne zu Baustelle?
% "	Was verhält sich zu Angela Merkel wie Adam zu Eva?
% "	Was verhält sich zu SPD wie Jesus zum Christentum?

% Capitals-Countries
V  = {'Deutschland' , 'Berlusconi' , 'Italien', ...
      'CDU', 'Donald_Trump', 'USA', ...
      'Deutschland', 'Queen_Elizabeth', 'Grossbritannien',...    
      'Deutschland', 'Abrissbirne', 'Haus',...
      'Angela_Merkel', 'Adam', 'Eva' , ... %'BASF', 'Seat', 'Volkswagen' ...
	  'SPD', 'Jesus', 'Christentum', ...    
      'Deutschland', 'Trump', 'USA' ...
	 };
    %,{'Merkel', 'Deutschland', ...
    %'Letta', 'Italien', ...
    %'Obama', 'USA',...
    %'Putin', 'Russland', ...
    %'Hollande', 'Frankreich', ...
    %}};

for k = 1:(numel(V)/3)
    idx = (k-1)*3 + 1;
    ref = m.vector(V{idx+1}) - m.vector(V{idx+2}) + m.vector(V{idx});   
    m.plotknn(ref, 50);
    title(sprintf('%s %s %s', V{idx:(idx+2)}), 'Interpreter', 'None')
    %h = gcf;
    %h.Position =  [66           1        1855        1001];
    %export_fig(sprintf('%s-%s-%s.jpg', V{idx:(idx+2)}),'-r256')
    %close(h);
    hold off
end



