% Capitals-Countries
V  = {{'Berlin', 'Deutschland', ...
    'Rom', 'Italien', ...
    'Brüssel', 'Belgien',...
    'Paris', 'Frankreich', ...
    'Madrid', 'Spanien', ...
    'Peking', 'China', ...
    'Warschau', 'Polen', ...
    'Moskau', 'Russland', ...
    'Dublin', 'Irland', ...
    'Washington', 'USA', ...
    'Lissabon', 'Portugal', ...
    'Athen', 'Griechenland'
    }};
    %,{'Merkel', 'Deutschland', ...
    %'Letta', 'Italien', ...
    %'Obama', 'USA',...
    %'Putin', 'Russland', ...
    %'Hollande', 'Frankreich', ...
    %}};

for k = 1:numel(V)
    vectors = V{k};
    figure;
    [~,idxA,idxB] = intersect(m.Terms, vectors);
    idxA(idxB) = idxA;
    idx = idxA;
    d = m.project2D(idx);
    
    %scatter(d(:,1), d(:,2), '.');
    hold on
    for i = 1:(numel(idx)/2)
        j = (i-1)*2 + 1;
        
        % Capital
        w1 = vectors{j};
        v1 = d(j, :);
        % Country
        w2 = vectors{j+1};
        v2 = d(j+1, :);
        
        text(v2(1), v2(2), w2)%, 'BackgroundColor', 'w');
        arrow(v1,v2, 'Length', 5);
        text(v1(1), v1(2), w1)%, 'BackgroundColor', 'w');
    end
    hold off
end
words = {'Beethoven', ...
    'Mozart', ...
    'Liszt', ...
    'Bach', ...
    'Bob_Dylan', ...
    'Metallica', ...
    'Black_Sabbath', ...
    'Queen', ...
    'Beatles', ...
    'Rolling_Stones', ...
    'Chopin', ...
    'Brahms', ...
    'Debussy', ...
    'Britney_Spears', ...
    'Lady_Gaga', ...
    'Rihanna', ...
    'Madonna', ...
    'Pink_Floyd'};

[~,idxA,idxB] = intersect(m.Terms, words);
idxA(idxB) = idxA;
idx = idxA;
figure; m.plot(idx);

v = m.vector('Italiener') - m.vector('Pizza') + m.vector('Baguette');
m.plotknn(v, 28);



